- apt:
  - build-essential
  - net-tools
  - openssh-server
  - zsh
  - zoxide
  - fzf
  - tree
  - tldr
  - tmux
  - screen
  - coreutils
  - moreutils
  - findutils
  - wget
  - imagemagick
  - ffmpeg